language: erlang
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=8b53d962594d0253d20002380cfb837fb81b928b
  email: eng@basho.com
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - ./rebar3 as prod compile
  - ./rebar3 as check xref
  - ./rebar3 as check dialyzer
  - ./rebar3 as test compile
  - BITCASK_IO_MODE=erlang ./rebar3 eunit
  - /bin/rm -rf /tmp/bc.* /tmp/bitcask.*
  - BITCASK_IO_MODE=nif ./rebar3 eunit
  - /bin/rm -rf /tmp/bc.* /tmp/bitcask.*
  - ./rebar3 edoc
otp_release:
  - 19.2
  - 18.3
  - 17.5
  - R16B03
